name: auto-sync-main
on:
  workflow_dispatch:
  schedule:
    - cron: '*/59 * * * *'

jobs:
  auto_sync_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #Fetches all commits

      - name: Configure Git Bot User
        run: |
          git config user.name "GitHub Action Bot"

      - name: Fetch Latest Changes
        run: git fetch origin

      - name: Checkout Team Branch
        run: git checkout main-side-app

      - name: Merge Master to Team Branch
        run: git merge origin/master --no-edit

      - name: Push Changes to Team Branch
        run: git push origin main-side-app