name: Lint Action
on: 
  push:
    branches:
      - main
      - samples/*

jobs:
  code-build:
    runs-on: ubuntu-latest
    steps:
      - name: code-checkout
        uses: actions/checkout@v4

      - name: build
        run: ./gradlew build

    
